Reinstate bouncy spongie
SpongePowered/SpongeHome pull request #129
Opened 2017-03-12 21:17 UTC by jamierocks

This was removed a while back, for not looking all too professional. However I think it adds some extra flare to the site and improves its overall look.

I also feel that it is fitting with the Sponge brand, with its playful aspects - something I would imagine would be good to promote, when the Sponge project literally revolves around a game.

Well thats my 2 cents anyway...

2017-03-12 21:32 UTC, jamierocks commented
so i be that very cool spongie auto bot thingy.

here ya go -> http://dev.jamiemansfield.me/spongehome/

2017-03-13 12:42 UTC, Spongy commented
Setting up PR reference, please wait...

2017-03-13 12:56 UTC, stephan-gh requested changes

2017-03-13 12:56 UTC, Minecrell commented on src/scss/_index_sections.scss
> +  @-webkit-keyframes spongieDance {
This is not needed, [autoprefixer](https://github.com/postcss/autoprefixer) will automatically handle adding the necessary prefixes.

2017-03-13 12:56 UTC, Minecrell commented on src/scss/_index_sections.scss
> +    -webkit-animation: spongieDance ease-in-out 3s infinite;
As above

2017-03-13 13:10 UTC, progwml6 commented
This was intentionally removed in the past. It can not go back in unless it is agreed upon by staff.

2017-03-13 15:03 UTC, Zidane commented
I understand the OP's sentiments but this won't be returning.

2017-03-13 15:03 UTC, closed without merging