[WIP] Staff Page
SpongePowered/SpongeHome pull request #150
Opened 2018-08-16 20:02 UTC by jamierocks

Currently this page does not display all of the same information as the [docs page](https://docs.spongepowered.org/stable/en-GB/about/staff.html) does. For that reason, this page is intended to supplement the docs page - giving a more graphic thanks to our team <3

---

![Screenshot](https://i.jamierocks.uk/9ljjj6YuW3.png)

---

The `staff.json` file has been produced from the structure present in the docs page, I have tried my best to get accurate GitHub profiles - though some may be incorrect, it would be a good idea to check your entries :)

(for future reference) I used the following Python script to get profile images:
```py
from urllib.request import urlopen
from bs4 import BeautifulSoup
import json

staff = []

with open('staff.json') as json_data:
    staff = json.load(json_data)

for group in staff['current']:
    for member in group['members']:
        if not member['img']:
            print(member['name'])
            resp = urlopen(member['url'])
            soup = BeautifulSoup(resp, "html.parser")

            member['img'] = soup.find('meta', {'property': 'og:image'})['content']

with open('staff.json', 'w') as outfile:
    json.dump(staff, outfile, indent=4)
```

2018-08-16 21:37 UTC, phase commented
Can the background for the leaders use

![https://www.spongepowered.org/assets/img/backgrounds/sponsors-content.jpg](https://www.spongepowered.org/assets/img/backgrounds/sponsors-content.jpg)

(https://www.spongepowered.org/assets/img/backgrounds/sponsors-content.jpg)

or a variation of it? Some solid colors in the same color scheme would work too.

2018-08-17 00:30 UTC, kashike commented
Can we not uppercase people's names?

2018-08-17 09:07 UTC, jamierocks commented
@kashike [wrote](https://github.com/SpongePowered/SpongeHome/pull/150#issuecomment-413723174)
> Can we not uppercase people's names?

We can, currently that list was taken directly from the docs page. If you'd like any changes ping me on IRC :)

2018-08-17 09:25 UTC, lucko commented on staff.json
> +                    "url": "https://github.com/Luck"
`https://github.com/lucko` :)

2018-08-17 14:44 UTC, Spongy commented
Setting up PR reference, please wait...

2018-08-17 17:16 UTC, phase commented
Can we make overflow circles center? It looks a little odd on the left.

2018-08-17 17:26 UTC, phase requested changes
Some avatars need updating.

The [Sponsors](https://www.spongepowered.org/sponsors) page also needs updating.

Also the names of some people are quite long and look awkward (check `mosemister` at the bottom), and on smaller resolutions it jumbles up.

![2018-08-17-102356_1920x1080_scrot](https://user-images.githubusercontent.com/7685133/44279918-0c9f3a80-a208-11e8-8d43-fccb4993ca3c.png)

2018-08-17 17:26 UTC, phase commented on staff.json
> +                    "img": "https://avatars2.githubusercontent.com/u/22254644?s=280&v=4",
`https://avatars0.githubusercontent.com/u/12867785?s=460&v=4`
`https://github.com/connorhartley`

2018-08-17 17:26 UTC, phase commented on staff.json
> +                    "url": "https://github.com/Luck"
Avatar: `https://avatars2.githubusercontent.com/u/8352868?s=460&v=4`
![](https://avatars2.githubusercontent.com/u/8352868?s=460&v=4)

2019-08-16 20:13 UTC, closed without merging